name: Der Medienlotse
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6e93c7'
    - '#555251'
    - '#b6c4e1'
    - '#837f7f'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
